name: Node-Python SpaCy Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        # Assuming SpaCy is listed in requirements.txt
        # If you need to install a specific SpaCy model, do it in the next step

    - name: Install SpaCy language model
      run: |
        python -m spacy download en_core_web_sm
        # Replace 'en_core_web_sm' with your desired model

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: |
        npm install

    - name: Run Node.js script
      run: node index.js
